name: "Build Nekoray"

on:
  workflow_dispatch:
    inputs:
      qt_version:
        description: 'Qt version'
        required: true
        default: '6.9.0'
      protobuf_version:
        description: 'Protobuf version'
        required: true
        default: 'v31.0'
      nekoray_version:
        description: 'Nekoray version to build'
        required: true
        default: 'abe2dc5'

jobs:
  build:
    runs-on: windows-2025
    env:
        CC: gcc.exe
        CXX: g++.exe
        QT_VERSION: ${{ github.event.inputs.qt_version }}
        PROTOBUF_VERSION: ${{ github.event.inputs.protobuf_version }}
        NEKORAY_VERSION: ${{ github.event.inputs.nekoray_version }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Export ImageVersion
      id: Set-ImageVersion
      run: echo "ImageVersion=$ImageVersion" && echo "ImageVersion=$ImageVersion" >> $GITHUB_OUTPUT

    # - name: Build Protobuf
    #   run: ./nekoray/protobuf.sh

    - name: Restore Qt cache
      id: restore
      uses: actions/cache/restore@v4
      with:
        path: build/qt6/build
        key: qt-${{ steps.Set-ImageVersion.outputs.ImageVersion }}-${{ env.QT_VERSION }}

    - name: Build Qt6 Static
      if: steps.restore.outputs.cache-hit != 'true'
      run: ./nekoray/qt6-static.sh

    - name: Save Qt cache if cache miss
      if: steps.restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: build/qt6/build
        key: qt-${{ steps.Set-ImageVersion.outputs.ImageVersion }}-${{ env.QT_VERSION }}
