name: "Build Nekoray"

on:
  workflow_dispatch:
    inputs:
      qt_version:
        description: 'Qt version'
        required: true
        default: '6.9.0'
      protobuf_version:
        description: 'Protobuf version'
        required: true
        default: 'v31.0'
      nekoray_version:
        description: 'Nekoray version to build'
        required: true
        default: 'abe2dc5'

jobs:
  build:
    runs-on: windows-2025
    env:
        CC: gcc.exe
        CXX: g++.exe
        QT_VERSION: ${{ github.event.inputs.qt_version }}
        PROTOBUF_VERSION: ${{ github.event.inputs.protobuf_version }}
        NEKORAY_VERSION: ${{ github.event.inputs.nekoray_version }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Build Protobuf
      run: ./nekoray/protobuf.sh
    
